### ISSUE TITLE
Use Constants for GUID, AUTHOR and MODNAME

### ISSUE THREAD

**Issue by harbingerofme** [risk-of-thunder/R2Boilerplate#8]
#2 is pointed to the wrong branch and cannot be merged auomatically

**Comment by harbingerofme** [comment]
We're looking for newcomers to Git to try and tackle this one!
[Here's a link to help you get started with how to contribute!](https://blog.devcenter.co/contributing-to-your-first-open-source-project-a-practical-approach-1928c4cbdae)
More links for this can be found [here](https://github.com/FreeCodeCamp/how-to-contribute-to-open-source)

**Comment by xiaoxiao921** [comment]
Fixed by #12
